// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectDAW.Data;

#nullable disable

namespace ProiectDAW.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215100000_AddUpdatedAtToGroupMessage")]
    partial class AddUpdatedAtToGroupMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot after this migration - same as ApplicationDbContextModelSnapshot
        }
    }
}

